added bulut-hizmetleri page and updated _sidebar.md
GuvendeKal/guvendekal.org pull request #146
Opened 2024-12-01 09:16 UTC by ramomen

2024-12-01 11:13 UTC, GokturkTalha commented
Projeye böyle bir sayfa eklemek ne kadar doğru bilmiyorum. Hemde içinde Google yada Amazon gibi servislerde bulunuyor, bunlar Güvende Kal projesinin felsefesine tamamen ters bence.

İlgili konu yani "bulut hizmetleri" genel olarak ticari hizmetler olacaktır, ayrıyetten ücretsiz hizmet sunan servislerde  bildiğim kadarıyla kimlik bilgileri ve kredi kartı bilgilerinizi vermeniz gerekiyor. Buna rağmen onaylanmama ihtimalide var tabii.

Sonuç olarak benim kanımca böyle bir sayfayı eklemek pek uygun olmayabilir. Diğer Maintainer arkadaşlarda fikrini belirtebilir.

2024-12-01 12:17 UTC, ramomen commented
Görüşleriniz ve geri bildiriminiz için teşekkür ederim. Gelen değerlendirmeleri ve proje felsefesini göz önünde bulundurduğumda, önerdiğim sayfanın mevcut haliyle Güvende Kal'ın hedefleriyle uyumlu olmadığını kabul ediyorum.

Özellikle dikkatimi çeken noktalar şunlar:

Önerilen birçok bulut hizmet sağlayıcısının gizlilik politikaları, kullanıcı verilerinin ticari amaçlarla analiz edilmesi veya üçüncü taraflarla paylaşılmasını içeriyor. Bu durum, projenin mahremiyet ve güvenlik odaklı yaklaşımıyla çelişiyor.
Ayrıca, bazı hizmetlerin kimlik veya kredi kartı bilgileri talep etmesi, kullanıcının kişisel bilgilerini riske atabileceği anlamına geliyor. Bu da felsefenin temel taşlarından biri olan kullanıcı gizliliğine aykırı.
Ancak bu konunun tamamen dışlanması yerine, mahremiyet dostu ve açık kaynaklı servislerle yeniden ele alınabileceğine inanıyorum. Örneğin:

Hetzner Cloud, Nextcloud, ProtonDrive gibi mahremiyet odaklı hizmetler bu listeye dahil edilebilir.
Listeye, bu servislerin gizlilik avantajları ve kullanıcı verilerinin nasıl korunduğunu vurgulayan açıklamalar eklenebilir.
Ayrıca, ticari hizmetlerin risklerini anlamalarına yardımcı olacak bilgilendirici bölümler de eklenebilir. Eğer uygun görürseniz, bu yönde bir düzenleme yaparak projeye daha uygun bir içerik hazırlamayı öneriyorum. Revize edilmiş haliyle, hem felsefeye daha uyumlu hem de kullanıcıların güvenli alternatifler keşfetmesini sağlayacak bir kaynak oluşturabiliriz.

2024-12-01 12:40 UTC, GokturkTalha commented
@ramomen proje bütünlüğüne baktığımız zaman bulut hizmetleri evet eklenebilir. -Proton Drive dosya depolama sayfasına eklenebilir bu arada-

Ancak "bulut hizmetleri" kategorisi daha niş bir kitleye hitap edecektir. Yani demek istediğim arama motorlarını, tarayıcıları yada e-posta hizmetlerini günümüzde herkes kullanır. Ancak "bulut hizmetlerini" belki bu kesmin %10-20'lik bir kısmı ancak kullanacaktır. 

Bu yinede eklememize engel değil mesela şifre yöneticilerinide herkes kullanmaz ancak şifre yöneticilerini önermemiz ve şifre yöneticilerin artılarını yazmamız insanların şifre yöneticisi kullanmaya teşvik eder yada 2FA uygulamalarıda aynı şekilde.

Ancak bulut servisleri önerdiğimizde herkes kullanacak mı? Bu önemli bence, evet niş bir kitle için yapılabilir ancak yapılacaksa bulut hizmetleri genel olarak sıkıntılı bir konu olacak bizim açımızdan. Çünkü sunucuların yedeklenmesi, güvenlik gibi pek çok unsuru bulunuyor. 

Örneğin biz bulut hizmetleri sayfasında OVH Cloud'u önerdik diyelim, ilgili firmanın veri merkezi bir kaç yıl önce cayır cayır yandı; Dünya'nın en büyük sunucu firmalarından birisi olmasına rağmen. Yani genel olarak evet bu durum her firmada ve her serviste (e-posta firmasının sunucusunda yangın çıkabilir) hatalar olabilir. Ancak demek istediğim nokta biz bir firmayı önerdiğimiz takdirde bir noktada da onun sorumluluğubu rnu almış oluyoruz, her ne kadar sorumluluk almıyoruz desekte.

Ve son olarakekleyeceklerim, mahremiyet ve gizlilik olarak kesinlikle ilgili hizmetler önerilmemeli. Genelde deniz aşırı ülkelerde paylaşımlı hostingler olur tahminimce bu firmalar senin kişisel verilerini de toplamıyordur, eğer önereceksekte bu tarz servisleri önemeliyiz gibi duruyor.

2024-12-01 12:56 UTC, ramomen commented
Bulut hizmetlerinin herkes için uygun bir konu olmadığına katılıyorum; ancak GitHub’da barındırılan ve geliştiricilere yönelik bir proje için bu kategorinin faydalı olabileceğini düşünüyorum. Teknik bir kitleye hitap eden bu tür bir rehber, mahremiyet dostu ve açık kaynaklı alternatifleri sunarak, doğru seçimler yapmalarına yardımcı olabilir.

Sorumluluk konusundaki endişelerinizi anlıyorum. Bu yüzden, rehberin yalnızca bilgilendirme amaçlı olduğunu netleştirebilir ve içerikte risklere dair uyarılar ekleyebiliriz. Ayrıca, kategori tamamen Nextcloud, ProtonDrive gibi mahremiyet odaklı hizmetlerle sınırlanarak, projenin felsefesiyle uyumlu hale getirilebilir. 

Konu hakkındaki görüşlerim ve önerilerim bu yöndedir. Bu konu üzerinde bir ısrarda bulunmayacağım.

2024-12-01 13:12 UTC, GokturkTalha commented
> Bulut hizmetlerinin herkes için uygun bir konu olmadığına katılıyorum; ancak GitHub’da barındırılan ve geliştiricilere yönelik bir proje için bu kategorinin faydalı olabileceğini düşünüyorum. Teknik bir kitleye hitap eden bu tür bir rehber, mahremiyet dostu ve açık kaynaklı alternatifleri sunarak, doğru seçimler yapmalarına yardımcı olabilir.
> 
> Sorumluluk konusundaki endişelerinizi anlıyorum. Bu yüzden, rehberin yalnızca bilgilendirme amaçlı olduğunu netleştirebilir ve içerikte risklere dair uyarılar ekleyebiliriz. Ayrıca, kategori tamamen Nextcloud, ProtonDrive gibi mahremiyet odaklı hizmetlerle sınırlanarak, projenin felsefesiyle uyumlu hale getirilebilir.
> 
> Konu hakkındaki görüşlerim ve önerilerim bu yöndedir. Bu konu üzerinde bir ısrarda bulunmayacağım.

@odest @islemci @conmecha @relliv ve @Sxinar sizlerinde fikirlerini duyabilir miyim?

2024-12-01 14:13 UTC, conmecha commented
Olabilir, herhangi bir yanlış bilgilendirme içermediği sürece bu konudaki içeriği eklemekte bir sorun olacağını sanmıyorum. Tabii belirtildiği gibi projenin amacına uygun olması şartıyla.

2024-12-01 14:26 UTC, relliv commented
Bulut bambaşka bir dünya ama diğer yandan self-hosted kavramını da destekleyen bir şey. Bende kararsız kaldım. Bu PR'ı 1-2 ay açık tutup sonrasında eğer hala ihtiyaç olduğu fikri güçlüyse dahil edelim diyorum.

2024-12-01 15:17 UTC, islemci requested changes
Bulut hizmetleri sayfasına bence bu proje için ihtiyacımız yok. (guvendekal.org SysAdmin rehberi değil, günlük kullanıcılar içindir.)

Artı olarak, Amazon - Google - Microsoft gibi şirketlerden uzaklaşmaya çalışırken kendi bulut sistemlerini kullanmak bana çok yanlış geliyor.

2024-12-01 16:22 UTC, GokturkTalha commented
Şimdilik draft'a çektim. Eğer gerekli görürsek düşünelim. Herkes tam karar veremedi gibi çünkü. Zamanla yeni insanlarda katıldıkça onlarda fikirlerini belirtir.

2024-12-01 18:56 UTC, Sxinar commented
> > Bulut kişiye herkes için uygun bir konu sistemi kurulur; Ancak GitHub'da barındırılan ve geliştiricilere yönelik bir proje için bu kategorinin faydalı olabileceğini düşünüyorum. Teknik bir kitleye hitap eden bu tür bir rehber, mahremiyet dostu ve açık kaynaklı alternatifleri sunarak, doğru seçimler yapılmasına yardımcı olabilir.
> > Sorumluluklarınızın endişelerinizi ortadan kaldırın. Bu nedenle, rehberin yalnızca bilgilendirme amaçlı olması netleştirilebilir ve içerikteki risklere ilişkin göstergeler gösterilebilir. Ayrıca kategori tamamen Nextcloud, ProtonDrive gibi mahremiyet odaklı hizmetlerle sınırlanarak, sağlıklı beslenmeyle uyumlu hale getirilebilir.
> > Konunun düzenlenmesi ve önerilerim bu yöndedir. Bu konu üzerinde bir ısrarda olmayacağım.
> 
> @odest @islemci @conmecha @rellivve@Sxinarsizlerinde duyabilir miyim?

Şahsen ben bulut hizmetlerinin çok daha alt alanlarda eklenmesi kanısındayım.
Nextcloud bir bulut hizmeti tamam ama WhatsApp , Facebook diğer medyalar da bulut hizmetleri.
Bunların ayrı başlıklarda incelenmesi yüzeysel incelemenin önüne geçerek mahremiyet odaklı olduğumuzu daha çok öne çıkartır diye düşünüyorum.

2024-12-13 20:14 UTC, closed without merging

2024-12-13 20:14 UTC, GokturkTalha commented
Üzerinden 2 hafta geçtiği için ilgili PR'ı kapatıyorum.