yeni-kategoriler-düzeltme-eklemeler
GuvendeKal/guvendekal.org pull request #190
Opened 2024-12-09 22:54 UTC by furkancamyar

"Torrent İstemcileri" kategorisine 2 yeni uygulama eklendi. "Not Alma" kategorisine 1 yeni uygulama eklendi. "Uygulamalar" bölümüne, İndirme Yöneticeleri, Yazılım Kaldırma Araçları, URL Kısaltıcılar ve QR Kod Oluşturma Araçları gibi yeni kategoriler ve bu kategorilere ait uygulamalar dahil edildi. Yapılan bu değişiklikler doğrultusunda README.md ve _sidebar.md dosyaları güncellendi. Ayrıca, "Android" kategorisindeki uygulama ikon boyutu düzenlendi.

2024-12-09 23:13 UTC, GokturkTalha requested changes
Genel olarak diğer ekleyeceğim şeyler, uygulama altlarında sırayla eklenen bilgilerin kullanıcıların kafasını karıştırabilir diye düşünüyorum, zaten önceden yazılmış bilgileride içerdiği için sadece kalabalık yapıyor olabilir mi? Örneğin zaten metin içinde zaten özgür yazılım olduğu belirtilmiş, devamında yine aynı şekilde lisans türü açıklanmış.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/README.md
> +<div class="custom-box">
Önerilen Uygulamalar kısmında büyük kutular içinde yer alan uygulamalar aslında güvenlik yada mahremiyet konusunda yarar sağlayan uygulamaları eklemek daha mantıklı olacaktır. Buraya qBittorrent koyup koymamak arasında koymamak daha mantıklı geliyor.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/indirme-yoneticileri.md
> +| İndirme Yöneticisi | Veri Gizliliği | Açık Kaynak | Reklam | Lisans Türü | Platform Desteği | Uzantı Desteği |
Tabloda "veri gizliliği" kısmının pek bir önemi yok gibi duruyor.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/not-alma.md
>  | Uygulama | Açık Kaynak | Lisans      | Platform Desteği                                                        | Lokal/Bulut |
Tabloda en sağda "platform desteği" kısmını bırakmak diğer sayfalarla aynı olacağından daha düzenli bir görüntü bırakacaktır aynı zamanda iconların en sağda sıralanması daha estetik duruyor bence.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/torrent-istemcileri.md
> +| Torrent İstemcisi | Veri Gizliliği | Açık Kaynak | Reklam | Lisans Türü | Platform Desteği |
Yine tabloda bulunan "veri gizliliği" ve "reklam" kısımlarının pek bir açıklayıcı tarafı yok gibi duruyor.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/url-qr-kod-araclari.md
> +| URL • QR Kod Araç Adı | Veri Gizliliği | Açık Kaynak | Reklam | Lisans Türü | Fiyatlandırma | Platform Desteği |
Tabloda "veri gizliliği" kısmı yine pek bir açıklayıcı özellik taşımıyor. Yine "URL • QR Kod Araç Adı"  tanımını anlayamadım.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/yazilim-kaldirma-araclari.md
> +| Yazılım Kaldırma Araç Adı | Veri Gizliliği | Açık Kaynak | Reklam | Lisans Türü | Platform Desteği |
Tabloda bulunan "veri gizliliği" ve "reklam" kısımları yine pek bir açıklayıcı özellik taşımıyor gibi.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/indirme-yoneticileri.md
> +!> İndirme yöneticilerinin bazıları, reklam veya gereksiz eklentiler yükleyebilir. Kurulum sırasında ek yazılımların yüklenmesini engellemek için dikkatli olun.
Sonuç olarak bizim önerdiğimiz uygulamalarda böyle şeyler olmayacaktır. Ondan bu kısmın metnin genel bütünlüğüne katkı yaptığını düşünmüyorum.

2024-12-09 23:13 UTC, GokturkTalha commented on docs/indirme-yoneticileri.md
> +**İndirme Yöneticeleri**, internet üzerinden dosya indirme sürecini hızlandırmak, kolaylaştırmak ve daha verimli hale getirmek için kullanılan yazılımlardır. Bu araçlar, özellikle büyük boyutlu dosya
Sanırım bu tarz uygulamalar önceden daha çok işe yarıyordu. Günümüzde eskisi gibi bir yarar sağlıyor mu bilmiyorum, bilen varsa söyleyebilir.

2024-12-09 23:16 UTC, GokturkTalha commented
@furkancamyar büyük katkınız dolayısıyla teşekkür ederim! URL kısaltma ve QR kod aslında ayrı şeyler, şimdi fark ettim. Ayrı şekilde sayfalara bölünebilir. Genel yorumlarımı ekledim, bazı değiştirilmesi gereken noktalar var özellikle kalabalık yapan bölümler var gibi (uygulamaların mark stili ile açıklandığı yerler özellikle). Ben şuanlık projenin başka bir bölümünü aktif şekilde değiştirmeye uğraşıyorum, ondan bu PR'ı şimdilik Draft'a çeviriyorum beraberce sorunları düzeltip çekelim.

2024-12-09 23:17 UTC, GokturkTalha commented
@islemci @odest @relliv @conmecha sizlerde değişikliklerle ilgili fikirlerinizi belirtebilir misiniz?

2024-12-11 20:37 UTC, GokturkTalha commented
> @GokturkTalha Merhalar, Geri bildiriminiz için teşekkür ederim! Haklısınız, URL kısaltma ve QR kod oluşturma araçları farklı konseptlere sahip, ancak bazı web siteleri bu iki işlevi bir arada sunduğu için tek bir başlık altında vermeyi tercih etmiştim. Yine de ayrı sayfalara bölünmesi daha mantıklı olabilir.
> 
> "Not Alma" bölümüyle ilgili herhangi bir değişiklik yapmadım, yalnızca 1 yeni uygulama ekledim. Size katılıyorum, "platform desteği" kısmının en sağda sıralanması daha estetik duruyor.
> 
> Ayrıca, yeni uygulamalar eklemeyi planlıyorum ve önerdiğiniz düzenlemelerle birlikte bu PR’ı tekrar düzenleyip göndereceğim. Geri bildiriminiz doğrultusunda, özellikle açıklamalarda gereksiz kalabalık yaratan bölümleri sadeleştirmeye dikkat edeceğim. Tekrar teşekkürler!

Teşekkürler, bu PR açık dursun bende bazı düzeltmeler yapacağım yakında.

2024-12-12 17:28 UTC, GokturkTalha commented
Bu PR'ı çekiyorum, çok birikmiş PR olduğundan ileride yaşanacak senkronizasyon hataları için çekiyorum. İleride bir sorun hâlinde düzeltme yaparız.

2024-12-12 17:34 UTC, GokturkTalha commented
Hataları düzeltip bunuda çekelim, senkronizasyon hataları çıkıyor çünkü. Bugün yarın düzeltmeleri yapacağım @furkancamyar sizinde haberiniz olsun hocam.

2024-12-12 20:07 UTC, islemci commented on docs/_sidebar.md
> +* [<i class="fa-solid fa-link"></i> URL • QR Kod](url-qr-kod-araclari.md)
link kısaltma ve qr oluşturma sanırsam.

2024-12-12 20:09 UTC, GokturkTalha commented on docs/_sidebar.md
> +* [<i class="fa-solid fa-link"></i> URL • QR Kod](url-qr-kod-araclari.md)
Onları ayırırız.

2024-12-14 14:13 UTC, closed without merging

2024-12-14 15:19 UTC, furkancamyar commented
@GokturkTalha merhabalar, çekme işlemi başaralı bir şekilde gerçekleşti mi?

2024-12-14 20:54 UTC, GokturkTalha commented
@furkancamyar bu PR'ı kapatmışsınız ondan kontrol edemiyorum

2024-12-14 21:18 UTC, furkancamyar commented
@GokturkTalha hocam, benim hatam yeni uygulama eklerken bir çakışma yaşadım ve bu PR'ın birleştirdiği düşünerek kapattım. Şuan mevcut PR tekrar görünür hale getiremiyorum çünkü yaptığım değişiklikleri mevcut branch üzerine eklemiştim. Şöyle yapacağım çakışma olmaması için yeni bir PR oluşturup tekrar göndereceğim.

2024-12-14 21:28 UTC, GokturkTalha commented
> @GokturkTalha hocam, benim hatam yeni uygulama eklerken bir çakışma yaşadım ve bu PR'ın birleştirdiği düşünerek kapattım. Şuan mevcut PR tekrar görünür hale getiremiyorum çünkü yaptığım değişiklikleri mevcut branch üzerine eklemiştim. Şöyle yapacağım çakışma olmaması için yeni bir PR oluşturup tekrar göndereceğim.

Commitleri ayrı branch olarak paylaşmadıysanız, yani main dalına yada başka bir dala birleştirdiyseniz sorun olmadan açabilirsiniz aynı değişiklikler ile hocam.

2024-12-14 21:46 UTC, furkancamyar commented
@GokturkTalha evet hocam baktım fakat bu ilk yolladığım PR ana depodan geri de büyük ihtimalle çakışmalar olabilir.

2024-12-14 22:29 UTC, furkancamyar commented
@GokturkTalha "Reopen Pull Request" butonunun aktif değil sanırım bir uyumsuzluk ve ve tekrar PR oluşturuyorum fakat önceki branch ait ve çakışmalar olacaktır.

2024-12-14 22:30 UTC, furkancamyar commented
@

2024-12-14 22:32 UTC, GokturkTalha commented
> @GokturkTalha "Reopen Pull Request" butonunun aktif değil sanırım bir uyumsuzluk ve ve tekrar PR oluşturuyorum fakat önceki branch ait ve çakışmalar olacaktır.

Tamamdır sorun yok artık manuel düzeltiriz o zaman hocam