"Not Alma" bölümüne "Notesnook/Joplin" Eklendi
GuvendeKal/guvendekal.org pull request #252
Opened 2024-12-26 17:22 UTC by furkancamyar

## Yapılan Değişikler 

Lütfen yaptığınız değişikleri önizleme olması açısından kısaca açıklayınız. Yaptığınız değişiklikler bir hatayı düzeltiyorsa veya bir özellik talebini çözüyorsa, bu soruna bağlantı verdiğinizden emin olun.

## Değişiklik Türü

Katkınız proje üzerinde ne tür bir değişikliğe eşit geliyor?
Uygun olan kutulara `x` işareti koyun.

- [x] Dökümantasyon eklemeleri yapıldı (yeni sayfalar, yeni uygulamalar)
- [ ] Dökümantasyon düzeltmeleri yapıldı (sayfa iyileştirmeleri, yazım hatalarının giderilmesi)
- [ ] Koda katkı yapıldı (CSS/JS ya da diğer unsurlar)
- [ ] Hatalar giderildi (kod ve diğerleri)

## Kontrol Listesi

Uygun olan kutulara `x` işareti koyun. Bunları PR oluşturduktan sonra da doldurabilirsiniz. Bunlardan herhangi biri hakkında emin değilseniz, sormaktan çekinmeyin. Yardım etmek için buradayız! Bu sadece kodunuzu birleştirmeden önce nelere bakacağımıza dair bir hatırlatmadır.

- [x] Yapılan değişiklerin kontrolleri yerel sitede yapıldı.
- [x] Eklemelerim markdown ve yazım kurallarına uygun.
- [x] Sayfaya tablo ekledim/ tabloyu düzenledim. (tabloda gereksiz sütunlar yok)
- [x] Sayfa düzeni, diğer sayfalardan farklı değil.
- [x] Eklediğim uygulama(lar) açık kaynak.
- [x] Uygulama logosunu ekledim.
- [ ] Eklediğim logo transparan.
- [ ] Eklediğim tarayıcı eklentisi mahremiyet ve güvenlik anlamında tarayıcıya artılar ekliyor.
- [x] Eklediğim uygulamanın açık kaynak deposunu ve gizlilik politikalarını ekledim.
- [ ] CSS/JS ve diğer kod düzeltmelerimde bir hata yok.
- [ ] Giderilen hataları test ettim.

## Diğer yorumlar

"Not Alma" bölümüne "Notesnook ve Joplin" Eklendi

2024-12-27 06:45 UTC, GokturkTalha commented
Katkınız için teşekkürler @furkancamyar 

Yılbaşı dolayısıyla işlerim biraz yoğun, ondan bakamamıştım, bu akşam inceleyeceğim.

@wiseweb-works işiniz yoksa yada bakmak istiyorsanız sizde bakabilirsiniz hocam.

2024-12-27 11:38 UTC, wiseweb-works requested changes

2024-12-27 11:38 UTC, wiseweb-works commented on docs/not-alma.md
> +| <span style="display: inline-block; vertical-align: middle;"><img src="docs/images/notesnook-icon.png" alt="notesnook" style="width: 30px; height: 30px;"> </span> <span style="display: inline-block
Notesnook AGPL değil [GPL 3.0 lisansına](https://github.com/streetwriters/notesnook?tab=GPL-3.0-1-ov-file) sahip

2024-12-27 11:38 UTC, wiseweb-works commented on docs/not-alma.md
> +| <span style="display: inline-block; vertical-align: middle;"><img src="docs/images/joplin-icon.png" alt="joplin" style="width: 30px; height: 30px;"> </span> <span style="display: inline-block; vert
Joplin de anladığım kadarıyla MIT değil [AGPL lisansına](https://github.com/laurent22/joplin?tab=License-1-ov-file) sahip.

Orjinal repo (https://github.com/joplin) indirme olarak başka bir repoya, maintainer'in sahsi reposuna, (https://github.com/laurent22/joplin) yönlendiriyor.

2024-12-27 11:38 UTC, wiseweb-works commented on docs/not-alma.md
> +| <span style="display: inline-block; vertical-align: middle;"><img src="docs/images/joplin-icon.png" alt="joplin" style="width: 30px; height: 30px;"> </span> <span style="display: inline-block; vert
Ayrıca ücretli olup olmadığından emin olmamakla birlikte cloud versiyonu da mevcut imiş.

2024-12-27 18:42 UTC, GokturkTalha commented
#28

2024-12-28 00:09 UTC, wiseweb-works commented
Joplin'in lisansı halen MIT olarak görünüyor.

2024-12-28 21:26 UTC, GokturkTalha commented
Genel düzenlemeler yapıldı, şuan yoğun olduğumdan, daha fazla bakabilecek durumda olmadığımdan ve sürenin uzamaması için çekiyorum. Herhangi bir sorun olursa bir dahaki genel güncelleme atacağım zaman düzeltirim. Katkınız için teşekkürler!

2024-12-28 21:26 UTC, merged

2024-12-28 21:30 UTC, furkancamyar commented
@GokturkTalha önemli değil ne demek. Gözüme çarpan eksik veya yanlış bilgi varsa ben de memnuniyetle genel olarak güncelleme yapabilirim.

2024-12-29 04:34 UTC, GokturkTalha commented
> @GokturkTalha önemli değil ne demek. Gözüme çarpan eksik veya yanlış bilgi varsa ben de memnuniyetle genel olarak güncelleme yapabilirim. 

Teşekkürler.