Rss istemcileri eklendi
GuvendeKal/guvendekal.org pull request #36
Opened 2024-10-10 20:06 UTC by 2013dogumeymen

2024-10-10 20:11 UTC, islemci commented
404'e yapılan editler eklenmeyecek.
503 dosyası eklenmeyecek.

2024-10-10 20:12 UTC, islemci requested changes
404, 503 editleri silinmelidir.

2024-10-10 20:13 UTC, 2013dogumeymen commented
tekrar mı pull requestr atmam gerekiyor?

2024-10-10 20:14 UTC, GokturkTalha commented
Merhaba  @2013dogumeymen neden 404 sayfasında değişmesi gerektiğini düşündüğün nedir? 503 sayfası eklemeye gerek yok.

2024-10-10 20:16 UTC, 2013dogumeymen commented
@GokturkTalha 404 daha açıklayıcı olur düşündüm, ama 503 gereksizdi zaten sildim

2024-10-10 20:34 UTC, GokturkTalha commented
Tablonun düzeltilmesi gerekiyor, gereksiz uzun yazılar kullanılmış gibi- yapay zeka ile yazılmışa benziyorlar. Başlıklar doğru kullanılmamış, değişik biçimlendirmeler (markup) kullanışmış gibi duruyor.

Kullanıcıya hangi uygulamayı seçeceği konusunda düzgün bir rehber gibi durmuyor aksine bunu okuyan kullanıcının kafasının daha fazla karışması ve seçememe ihtimali yüksek gibi geliyor.

https://guvendekal.org/#/arama-motorlari

@2013dogumeymen bu yazıyı kontrol ederseniz ne demek istediğimi anlarsınız.

@islemci sizin fikriniz sadece 404 ve 503'ün silinmesi mi?

2024-10-10 20:45 UTC, 2013dogumeymen commented
@GokturkTalha tabloların nasıl oluştuğunu pek bilmediğimden chatgpt’ye yaptırdım mantığını anladım akşam olduğu için pek iyi yapamamış olabilirim düzelteceğim

2024-10-11 08:41 UTC, GokturkTalha commented
> Tablonun düzeltilmesi gerekiyor, gereksiz uzun yazılar kullanılmış gibi- yapay zeka ile yazılmışa benziyorlar. Başlıklar doğru kullanılmamış, değişik biçimlendirmeler (markup) kullanışmış gibi duruyor.
> 
> Kullanıcıya hangi uygulamayı seçeceği konusunda düzgün bir rehber gibi durmuyor aksine bunu okuyan kullanıcının kafasının daha fazla karışması ve seçememe ihtimali yüksek gibi geliyor.
> 
> https://guvendekal.org/#/arama-motorlari
> 
> @2013dogumeymen bu yazıyı kontrol ederseniz ne demek istediğimi anlarsınız.

Burada dediğim çoğu şey hâlâ geçerli.

Feedreader'in sitesi açılmıyor.

Linux ağırlıklı- KDE'ye özel bir uygulama bile eklenmiş ancak IOS için RSS okuyucu (yada platformlara eklenmemiş bilmiyorum) eklenmemiş.

Dediğim gibi içeriği okuyacak kişilerin büyük çoğunluğu windows, android, macos, ios kullanacak kişiler olacaktır belki. Bu içerik "Linux için RSS okuyucuları" gibi duruyor.

Feeder'in f-droid linkinin verilmesi iyi olarak düşünülebilir ancak bu içeriği okuyacak kaç kişi f-droid kullanacak?

"#" yerine 1- 2- 3- kullanılmış böyle kullanılmaması lazım, kullanım alanları niye var? yada başlıca özellikler bölümünde çok uzun ve gereksiz yazılar var, birinde olan özellik diğerinde de var. Bu kullanıcılara spesifik bir uygulama seçtirmeyecek bir düzendir çünkü içerik çok karmaşık. Okuyucunun daha da kafası karışıp hiç seçim yapamacaktır.

![Ekran Görüntüsü - 2024-10-11 11-37-20](https://github.com/user-attachments/assets/895e9581-0a71-4c6c-9856-731c66604952)

![Ekran Görüntüsü - 2024-10-11 11-38-18](https://github.com/user-attachments/assets/510a0e5e-28c3-4a08-a496-f0a379f3f2f3)

İki sayfa arasında ki farka bakarsanız demek istediğimi anlarsınız.

2024-10-20 20:06 UTC, closed without merging